# Per-host config for omnibook. Generated by scripts/setup-host.sh on first
# sync; safe to hand-edit. Delete this file to re-prompt on next sync.
HOST_DEV_TOOLS := 1
HOST_RESTIC    := 1
HOST_DROP_PKGS :=
HOST_NO_AAAA   := 1
