-- Hyprland config — Lua format (0.55+).
-- Converted from hyprland.conf; see https://wiki.hypr.land/Configuring/
--
-- Split across files via require(). monitors/workspaces are regenerated by
-- hypr-monitor on every hotplug; colors by theme-apply. Do not edit those.

------------------
---- MONITORS ----
------------------

-- monitors.lua and workspaces.lua do not exist until hypr-monitor first runs.
-- hyprlang's `source` warned and carried on when a file was missing, but Lua's
-- require is fatal and would abort the rest of this file, leaving a fresh
-- machine with no binds at all. Tolerate absent; still surface a generated file
-- that exists but is malformed, rather than silently skipping it.
local function require_generated(name)
    local ok, err = pcall(require, name)
    if ok or tostring(err):match("^module '" .. name .. "' not found") then
        return
    end
    error(err, 0)
end

require_generated("monitors")
require_generated("workspaces")
local clr = require("colors")


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "thunar"
local menu        = "rofi -show drun"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd([[waybar 2>&1 | grep -v 'Gtk-CRITICAL\|GTK_IS_ACCEL_GROUP' &]])
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("swaync")
    hl.exec_cmd("~/.local/bin/hypr-urgent-focus")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("udiskie --smart-tray")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("~/.local/bin/hypr-battery-monitor &")
    hl.exec_cmd("~/.local/bin/laptop-watchdog &")
    hl.exec_cmd("playerctld daemon")

    -- Workspace management daemons
    hl.exec_cmd("hyprscratch init")
    hl.exec_cmd("hyprwhenthen run")
    hl.exec_cmd("sleep 1 && ~/.local/bin/hypr-monitor watch")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- XDG
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- Qt
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")

-- GPU — hybrid Intel/NVIDIA (Intel primary, NVIDIA via prime-run)
hl.env("LIBVA_DRIVER_NAME", "iHD")
hl.env("AQ_DRM_DEVICES", "/dev/dri/card0:/dev/dri/card1")

-- Firefox
hl.env("MOZ_ENABLE_WAYLAND", "1")

-- Electron/Chromium
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")


-----------------------
----- PERMISSIONS -----
-----------------------

-- Permission changes require a Hyprland restart and are not applied on-the-fly
-- for security reasons.

hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(bin|local/bin)/hyprlock", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in         = 5,
        gaps_out        = { 10, 20, 20, 20 },
        gaps_workspaces = 50,

        border_size = 2,

        col = {
            active_border   = { colors = { clr.active_1, clr.active_2 }, angle = 45 },
            inactive_border = clr.inactive,
        },

        -- Resize windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/
        allow_tearing = true,

        layout = "dwindle",

        snap = {
            enabled = true,
        },
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = clr.shadow,
        },

        blur = {
            enabled  = true,
            size     = 5,
            passes   = 2,

            popups   = true,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

--                NAME              TYPE      POINTS
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1} } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1} } })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })
hl.animation({ leaf = "borderangle",   enabled = true, speed = 100,  bezier = "linear",       style = "loop" })

-- "Smart gaps" / "No gaps when only" — uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

hl.config({
    dwindle = {
        preserve_split       = true,
        special_scale_factor = 0.8,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper  = 0,
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms  = true,
        key_press_enables_dpms   = true,
        middle_click_paste       = false,
        focus_on_activate        = true,
        allow_session_lock_restore = true,
        enable_swallow           = true,
        swallow_regex            = "^(kitty)$",
        swallow_exception_regex  = [[^(org\.pwmt\.zathura)$]],
    },

    cursor = {
        no_hardware_cursors = 1,
    },

    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles   = true,
    },
})

-- Scratchpad: semi-transparent overlay
hl.workspace_rule({ workspace = "special:󰏫", gaps_out = 30 })
hl.window_rule({
    name  = "scratchpad-see-through",
    match = { workspace = "special:󰏫" },

    opacity = 0.85,
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout    = "us",
        repeat_rate  = 50,
        repeat_delay = 300,

        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll       = true,
            disable_while_typing = true,
            tap_to_click         = true,
        },
    },
})

-- Touchpad gestures
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Example per-device config
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Q",         hl.dsp.exec_cmd("env LAUNCH_TMUX=1 " .. terminal))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C",         hl.dsp.window.close())
hl.bind(mainMod .. " + E",         hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V",         hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R",         hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo())                          -- dwindle
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("~/.local/bin/hypr-pin-toggle")) -- sticky window
hl.bind(mainMod .. " + T",         hl.dsp.layout("togglesplit"))                    -- dwindle

-- Screenshots — see ~/.local/bin/screenshot.
-- Modifiers: (none)=full, SHIFT=region, SUPER=window, SUPER+SHIFT=focused monitor;
--            CTRL=clipboard only (no disk).
hl.bind("Print",                     hl.dsp.exec_cmd("screenshot full copy"))
hl.bind("SHIFT + Print",             hl.dsp.exec_cmd("screenshot region copy"))
hl.bind(mainMod .. " + Print",       hl.dsp.exec_cmd("screenshot window copy"))
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("screenshot monitor copy"))
hl.bind("CTRL + Print",              hl.dsp.exec_cmd("screenshot region clip"))

-- Clipboard history
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(
    [[cliphist list | rofi -dmenu | cliphist decode | wl-copy && sleep 0.05 && if hyprctl activewindow -j | jq -r '.class' | grep -qiE '^(kitty|foot|Alacritty|wezterm)$'; then wtype -M ctrl -M shift v; else wtype -M ctrl v; fi]]
))

-- Lock screen
hl.bind(mainMod .. " + escape", hl.dsp.exec_cmd("loginctl lock-session"))

-- Fullscreen
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())

-- Browser
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("firefox-developer-edition"))

-- Toggle waybar
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(
    [[pkill waybar || waybar 2>&1 | grep -v 'Gtk-CRITICAL\|GTK_IS_ACCEL_GROUP' &]]
))

-- Notifications
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("swaync-client -t"))

-- Game mode (disable effects for performance)
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("~/.local/bin/hypr-gamemode"))

-- Night light (blue light filter)
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("~/.local/bin/hypr-nightlight-toggle"))

-- Keybind cheatsheet
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("~/.local/bin/hypr-keybind-cheatsheet"))

-- Wallpaper manager (switches to empty workspace first so desktop is visible)
hl.bind(mainMod .. " + ALT + W", hl.dsp.exec_cmd("~/.local/bin/hypr-wallpaper-open"))

-- Settings menu (Wi-Fi, Bluetooth, Audio, Display, Appearance, System Monitor)
hl.bind(mainMod .. " + semicolon", hl.dsp.exec_cmd("~/.local/bin/hypr-settings-menu"))

-- Read screen aloud (toggle — press again to stop)
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("~/.local/bin/hypr-read-screen"))

-- Taildrop: send files to a tailnet device (+CTRL sends the clipboard)
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("~/.local/bin/taildrop-send"))
hl.bind(mainMod .. " + CTRL + SHIFT + D", hl.dsp.exec_cmd("~/.local/bin/taildrop-send --clip"))

-- Move focus with mainMod + hjkl
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Cycle floating windows (focus only reaches tiled windows in dwindle)
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.cycle_next({ floating = true }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.bring_to_top())

-- Swap windows with mainMod + SHIFT + hjkl
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.swap({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.swap({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.swap({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.swap({ direction = "down" }))

-- Switch workspaces / move active window with mainMod (+ SHIFT) + [1-9]
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end

-- 0 is the tray workspace (scripted)
hl.bind(mainMod .. " + 0",         hl.dsp.exec_cmd("hypr-tray-toggle"))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.exec_cmd("hypr-tray-move"))

-- Move all windows in active workspace to target workspace with mainMod + CTRL + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + CTRL + " .. key,
        hl.dsp.exec_cmd("~/.local/bin/hypr-move-workspace-to " .. i))
end

-- Move active workspace to adjacent monitor
hl.bind(mainMod .. " + CTRL + comma",  hl.dsp.exec_cmd("~/.local/bin/hypr-move-ws-monitor -1"))
hl.bind(mainMod .. " + CTRL + period", hl.dsp.exec_cmd("~/.local/bin/hypr-move-ws-monitor +1"))

-- Re-apply monitor layout + workspace assignments (fixes stranded workspaces)
hl.bind(mainMod .. " + CTRL + R", hl.dsp.exec_cmd("~/.local/bin/hypr-monitor assign"))

-- Scratchpad. Native dispatchers, not `hyprctl dispatch` — under a Lua config the
-- legacy string form is rejected outright. The second bind on each key nudges the
-- waybar scratchpad/tray indicators, which have no event to hook.
local refreshSpecialWaybar = hl.dsp.exec_cmd("pkill -RTMIN+9 waybar; pkill -RTMIN+10 waybar")

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("󰏫"))
hl.bind(mainMod .. " + S", refreshSpecialWaybar)
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:󰏫" }))
hl.bind(mainMod .. " + SHIFT + S", refreshSpecialWaybar)

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Move project (all windows + name) to next/prev monitor's empty slot
hl.bind(mainMod .. " + CTRL + right", hl.dsp.exec_cmd("~/.local/bin/hypr-move-project next"))
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.exec_cmd("~/.local/bin/hypr-move-project prev"))

-- --- Named workspaces (rofi) ---
local wsMgr = "~/.local/bin/hypr-dynamic-workspaces"

hl.bind(mainMod .. " + Z",         hl.dsp.exec_cmd(wsMgr .. " --workspace-switcher"))
hl.bind(mainMod .. " + SHIFT + Z", hl.dsp.exec_cmd(wsMgr .. " --move-window"))
hl.bind(mainMod .. " + BackSpace", hl.dsp.exec_cmd(wsMgr .. " --delete-current-workspace"))
hl.bind(mainMod .. " + ALT + space", hl.dsp.exec_cmd(wsMgr .. " --window-switcher"))

-- Sequential workspace navigation (desktop-contained, non-empty only)
hl.bind(mainMod .. " + Tab",         hl.dsp.exec_cmd("~/.local/bin/hypr-tab-nonempty"))
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.exec_cmd("~/.local/bin/hypr-tab-nonempty prev"))

-- Resize submap (SUPER+A to enter, hjkl to resize, Esc to exit)
hl.bind(mainMod .. " + A", hl.dsp.submap("resize"))
hl.define_submap("resize", "reset", function()
    -- relative = true, else x/y are treated as an absolute target size
    hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0,   relative = true }), { repeating = true })
    hl.bind("l", hl.dsp.window.resize({ x = 10,  y = 0,   relative = true }), { repeating = true })
    hl.bind("k", hl.dsp.window.resize({ x = 0,   y = -10, relative = true }), { repeating = true })
    hl.bind("j", hl.dsp.window.resize({ x = 0,   y = 10,  relative = true }), { repeating = true })
    hl.bind("escape",   hl.dsp.submap("reset"))
    hl.bind("catchall", hl.dsp.submap("reset"))
end)

-- Volume and brightness (SwayOSD, with a partial fallback)
--
-- The `|| ...` fallbacks only cover SwayOSD being *absent*. swayosd-client
-- exits non-zero when nothing owns the bus name, but exits 0 when a server
-- answers and refuses the call -- which is what a server still running a
-- binary that an upgrade deleted does, so these keys go silently dead until it
-- restarts. `make sync` now handles that; see ISSUES.md.
--
-- Do not "fix" this by calling busctl with a literal signature here: the
-- signature is what moved in swayosd 0.3.1 -> 0.3.2, so pinning it just
-- re-breaks on the next bump. Probing the server costs more than the keypress.
hl.bind("XF86AudioRaiseVolume",
    hl.dsp.exec_cmd("swayosd-client --output-volume raise 2>/dev/null || wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",
    hl.dsp.exec_cmd("swayosd-client --output-volume lower 2>/dev/null || wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMute",
    hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle 2>/dev/null || wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",
    hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle 2>/dev/null || wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
    { locked = true, repeating = true })

-- Brightness (see the note above)
hl.bind("XF86MonBrightnessUp",
    hl.dsp.exec_cmd("swayosd-client --brightness raise 2>/dev/null || brightnessctl -e4 -n2 set 5%+"),
    { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",
    hl.dsp.exec_cmd("swayosd-client --brightness lower 2>/dev/null || brightnessctl -e4 -n2 set 5%-"),
    { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Calculator key: qalc in a new tmux pane if focused terminal has tmux, else floating kitty
hl.bind("XF86Calculator", hl.dsp.exec_cmd("~/.local/bin/hypr-qalc"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({
    -- Ignore maximize requests from all apps.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Picture-in-Picture
hl.window_rule({
    name  = "pip-float",
    match = { title = [[^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)$]] },

    float             = true,
    pin               = true,
    keep_aspect_ratio = true,
    size              = "25% 25%",
    move              = "73% 72%",
})

-- Inhibit idle when fullscreen (browsers, media players)
hl.window_rule({
    name  = "idle-inhibit-fullscreen",
    match = {
        fullscreen = true,
        class      = "^(firefox-developer-edition|firefox|microsoft-edge.*|[Gg]oogle-chrome|brave-browser|mpv|vlc|celluloid)$",
    },

    suppress_event = "idle",
})

-- Float common dialogs
hl.window_rule({
    name  = "float-dialogs",
    match = { class = "^(nm-connection-editor|org.gnome.Calculator|xdg-desktop-portal-gtk)$" },

    float = true,
})

hl.window_rule({
    name  = "float-file-dialogs",
    match = { title = "^(Open File|Save File|Save As|Confirm|File Upload)$" },

    float = true,
})

-- Floating TUI apps (nmtui, btop, etc.)
hl.window_rule({
    name  = "float-tui",
    match = { class = "^(floating-tui)$" },

    float  = true,
    size   = "800 600",
    center = true,
})

-- TUI popup menus
hl.window_rule({
    name  = "wallpaper-popup",
    match = { class = "^(hypr-wallpaper-menu)$" },

    float  = true,
    size   = "460 420",
    center = true,
})

-- Thunderbird — float compose/reply windows, keep main tiled
hl.window_rule({
    name  = "thunderbird-compose-float",
    match = {
        class = [[^(org\.mozilla\.Thunderbird)$]],
        title = "^(Write:|Re:|Fwd:)",
    },

    float  = true,
    size   = "800 600",
    center = true,
})

-- Thunderbird/Zotero — prevent focus-stealing when hidden in tray workspace
hl.window_rule({
    name  = "tray-apps-no-activate",
    match = { class = [[^(org\.mozilla\.Thunderbird|Zotero)$]] },

    suppress_event = "activate",
})


---------------------
---- LAYER RULES ----
---------------------

hl.layer_rule({
    name  = "waybar-blur",
    match = { namespace = "waybar" },

    blur         = true,
    xray         = true,
    ignore_alpha = 0.5,
})

hl.layer_rule({
    name  = "swaync-notification-blur",
    match = { namespace = "swaync-notification-window" },

    blur         = true,
    ignore_alpha = 0.5,
})

hl.layer_rule({
    name  = "swaync-control-center-blur",
    match = { namespace = "swaync-control-center" },

    blur         = true,
    ignore_alpha = 0.5,
})
