# hyprscratch configuration
# Docs: https://github.com/sashetophizika/hyprscratch

daemon_options = clean
global_options = special
global_rules = size 80% 80%

term {
    title = scratchpad-term
    command = kitty --title scratchpad-term
    options = persist
    rules = size 80% 80%
}

music {
    title = spotify_player
    command = kitty --title spotify_player -e spotify_player
    options = persist
    rules = size 70% 80%
}
