# hyprscratch configuration
# Docs: https://github.com/sashetophizika/hyprscratch

daemon_options = clean
global_options = special
global_rules = size 80% 80%

󰏫 {
    title = scratchpad-term
    command = kitty --title scratchpad-term
    options = persist
    rules = size 80% 80%
}

