-- Colorscheme: mini.base16 fed the generated Solarized palette (base16 form).
-- theme_colors.lua is regenerated by theme-apply, which also RPC-reloads
-- running nvims via require('mini.base16').setup{palette=require('theme_colors'),...}
-- config.diff_hl re-applies word-diff preview colors after every base16 setup.
return {
  { 'folke/tokyonight.nvim', enabled = false },
  { 'catppuccin/nvim', enabled = false },

  {
    'nvim-mini/mini.base16',
    lazy = false,
    priority = 1000,
    config = function()
      local diff_hl = require 'config.diff_hl'
      diff_hl.hook_base16()
      require('mini.base16').setup {
        palette = require 'theme_colors',
        use_cterm = true,
      }
      diff_hl.apply()
    end,
  },

  {
    'LazyVim/LazyVim',
    opts = {
      colorscheme = function()
        require('config.diff_hl').hook_base16()
        require('mini.base16').setup {
          palette = require 'theme_colors',
          use_cterm = true,
        }
        require('config.diff_hl').apply()
      end,
    },
  },
}
