-- Colorscheme: mini.base16 fed the generated Solarized palette (base16 form).
-- theme_colors.lua is regenerated by theme-apply, which also RPC-reloads
-- running nvims via require('mini.base16').setup{palette=require('theme_colors'),...}
return {
  { 'folke/tokyonight.nvim', enabled = false },
  { 'catppuccin/nvim', enabled = false },

  {
    'nvim-mini/mini.base16',
    lazy = false,
    priority = 1000,
    config = function()
      require('mini.base16').setup {
        palette = require 'theme_colors',
        use_cterm = true,
      }
    end,
  },

  {
    'LazyVim/LazyVim',
    opts = {
      colorscheme = function()
        require('mini.base16').setup {
          palette = require 'theme_colors',
          use_cterm = true,
        }
      end,
    },
  },
}
