#!/usr/bin/env bash
# setup-host.sh: write hosts/<hostname>.sh on first sync of a new machine.
# Idempotent: does nothing if the file already exists.
#
# Interactive run (TTY available): prompts for each flag, persists answers.
# Non-interactive (no TTY, or NONINTERACTIVE=1): writes conservative defaults
# without prompting and prints what was written.

set -euo pipefail

DOTFILES="${DOTFILES:-$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.." && pwd)}"
HOSTNAME="${HOSTNAME_OVERRIDE:-$(uname -n)}"
HOST_FILE="$DOTFILES/hosts/$HOSTNAME.sh"

mkdir -p "$DOTFILES/hosts"

if [ -f "$HOST_FILE" ]; then
  exit 0
fi

# Generic-looking hostnames suggest the OS installer never collected one.
case "$HOSTNAME" in
  archlinux|ubuntu|debian|localhost|localhost.localdomain|"")
    echo "WARNING: hostname is '$HOSTNAME' — looks like a default. Set a real one with:" >&2
    echo "  sudo hostnamectl set-hostname <name>" >&2
    echo "  (then log out and back in, and re-run 'make sync')" >&2
    echo "  Continuing with defaults for now." >&2
    ;;
esac

# Defaults
DEV=0
RESTIC=1
SSHFS_SKIP=""
DROP=""

# Mirror lib.sh's distro detection so we can skip Arch-only prompts. (Kept
# local rather than sourcing lib.sh: this runs before the host file exists.)
if command -v pacman >/dev/null 2>&1; then
  DISTRO_FAMILY=arch
else
  DISTRO_FAMILY=other
fi

if [ -t 0 ] && [ -t 1 ] && [ "${NONINTERACTIVE:-0}" != 1 ]; then
  echo
  echo "==> First sync on this host ('$HOSTNAME')."
  echo "    Quick setup — answers persist to hosts/$HOSTNAME.sh."
  echo "    Defaults shown in [brackets]; press Enter to accept."
  echo

  if [ "$DISTRO_FAMILY" = arch ]; then
    read -r -p "    Build hypr-tools from submodule (overrides AUR)? [y/N] " ans
    case "$ans" in y|Y|yes|YES) DEV=1 ;; esac
  fi

  read -r -p "    Enable restic backups to homelab Nextcloud? [Y/n] " ans
  case "$ans" in n|N|no|NO) RESTIC=0 ;; esac

  read -r -p "    sshfs mounts to skip (any of: ice cdn msi; blank for none): " SSHFS_SKIP

  read -r -p "    Stow packages to skip on this host (space-separated, blank for none): " DROP
fi

cat > "$HOST_FILE" <<EOF
# Per-host config for $HOSTNAME. Generated by scripts/setup-host.sh on first
# sync; safe to hand-edit. Delete this file to re-prompt on next sync.
# Sourced by scripts/lib.sh — plain shell assignments only.
HOST_DEV_TOOLS=$DEV
HOST_RESTIC=$RESTIC
HOST_SSHFS_SKIP="$SSHFS_SKIP"
HOST_DROP_PKGS="$DROP"
EOF

echo "    Wrote $HOST_FILE:"
sed 's/^/      /' "$HOST_FILE"
echo
echo "    Commit it: git add hosts/$HOSTNAME.sh && git commit -m 'add $HOSTNAME host config'"
