-- Generated by theme-apply — do not edit
-- base16 palette consumed by mini.base16 (see nvim/init.lua)
return {
  base00 = "#141c1e", -- default background
  base01 = "#20282a", -- lighter bg (status, line highlight)
  base02 = "#2f3739", -- selection background
  base03 = "#778184", -- comments, invisibles
  base04 = "#929ca0", -- dark foreground (line numbers)
  base05 = "#cfdadc", -- default foreground
  base06 = "#b6c0c2", -- light foreground
  base07 = "#9da7a9", -- lightest (rarely used)
  base08 = "#cf7f79", -- variables, errors
  base09 = "#ca865e", -- constants, numbers
  base0A = "#b0954a", -- classes, search
  base0B = "#70a971", -- strings
  base0C = "#43ac9b", -- support, regex
  base0D = "#609fd2", -- functions
  base0E = "#9d8ccf", -- keywords
  base0F = "#cf7e84", -- deprecated, brackets
}
