-- Generated by theme-apply — do not edit
-- base16 palette consumed by mini.base16 (see nvim/init.lua)
return {
  base00 = "#141c1e", -- default background
  base01 = "#20282a", -- lighter bg (status, line highlight)
  base02 = "#2f3739", -- selection background
  base03 = "#565f62", -- comments, invisibles
  base04 = "#848e91", -- dark foreground (line numbers)
  base05 = "#cfdadc", -- default foreground
  base06 = "#b6c0c2", -- light foreground
  base07 = "#9da7a9", -- lightest (rarely used)
  base08 = "#ab5e59", -- variables, errors
  base09 = "#a6653e", -- constants, numbers
  base0A = "#8e7426", -- classes, search
  base0B = "#4f8751", -- strings
  base0C = "#118a7a", -- support, regex
  base0D = "#3f7dae", -- functions
  base0E = "#7c6bac", -- keywords
  base0F = "#aa5d64", -- deprecated, brackets
}
